### ISSUE TITLE
Script breaks on mount options remount-ro,utf8 for ext3

### ISSUE THREAD

**Issue by killemov** [Ferk/udev-media-automount#10]
In `/etc/media-automount.d/auto` I had to change:
`AUTOMOUNT_OPTS=remount-ro,relatime,utf8,user,sync`
to
`AUTOMOUNT_OPTS=relatime,user,sync`
To make it work for ext3 partitions on natively connected SATA-drives.

```
uname -a
Linux buster 6.0.0-odroid-arm64 #1 SMP PREEMPT Debian 6.0.2-202210171716~bullseye (2022-10-17) aarch64 GNU/Linux
```

**Comment by Ferk** [comment]
I've fixed it in last release.
Thank you for the report, @killemov.

**Comment by killemov** [comment]
Maybe I wasn't clear enough in my issue statement: The utf8 option also appears to be a mount-breaker. It fails to mount an ext3 partition.
```
mount --version
mount from util-linux 2.36.1 (libmount 2.36.1: selinux, smack, btrfs, namespaces, assert, debug)
```
Using NO options would probably be the best way forward.

**Comment by Ferk** [comment]
Ow, sorry for the misunderstandment.
I think you are right, `mount` already has ok defaults. Though I'd like to have `users` just so the umount script can unmount without elevated priviledges.
I've removed the other options in 429e4452a51eb59f141fbc9675eb02c33c28ffdb.
