### ISSUE TITLE
Add installation instructions to README.md

### ISSUE THREAD

**Issue by killemov** [Ferk/udev-media-automount#11]
Download https://github.com/Ferk/udev-media-automount/archive/refs/heads/master.zip.
unzip master.zip
cd udev-media-automount-master
make install
udevadm control --reload-rules && udevadm trigger

**Comment by Ferk** [comment]
Thank you very much @killemov!!

I've added the instructions to the README as you suggested. Let me know if you would like any other change.

Sorry for the delay in the responses.
