### ISSUE TITLE
umount_dmenu not working?

### ISSUE THREAD

**Issue by jtannenba** [Ferk/udev-media-automount#18]
I have install this on Debian Bullseye.  I have yet to get umount_dmenu to work.  Cannot find what the proper command line options are.  Also on Debian, I had to install dmenu.

**Comment by Ferk** [comment]
There's no command line parameters for that script.

It's just a convenience script for listing the mounted filesystems in /media/ and using a GUI interface (via dmenu) to select one to unmount.

What's the error you are getting?

**Comment by jtannenba** [comment]
Oh, Thank you.  I was trying to use it in just a ssh shell.
