### ISSUE TITLE
/usr/bin -> /bin ?

### ISSUE THREAD

**Issue by archenemies** [Ferk/udev-media-automount#2]
I ran into problems on Raspbian which were (I think) resolved with the attached patch. Since /bin/ is a symlink to /usr/bin/ on my other (Arch) system, and likewise for /lib/, the change should have no effect.

[0001-Use-bin-not-usr-bin.patch.txt](https://github.com/Ferk/udev-media-automount/files/3124632/0001-Use-bin-not-usr-bin.patch.txt)

Are there systems where it has to be /usr/bin/systemctl?

**Comment by morganchristiansson** [comment]
Thank you this was required to run it on Raspbian

**Comment by clach04** [comment]
Cross reference https://github.com/Ferk/udev-media-automount/issues/4#issuecomment-573370772

**Comment by killemov** [comment]
The merge is coming. See https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/

**Comment by Ferk** [comment]
The scripts now use `/bin/sh`, I've also removed the dependency on bash.

Thanks and sorry for the delay.
