### ISSUE TITLE
Automounting DVD's

### ISSUE THREAD

**Issue by ocroquette** [Ferk/udev-media-automount#27]
I use udev-media-automount to mount external devices in a media server running Debian and UMS. It works great with mass storage devices like hard drives and USB sticks. Now I am trying to make it work for (video) DVD's.

The DVD drive shows up as /dev/sr0.
I can mount it manually:
```
mount /dev/sr0 /mnt/tmp
```

I have added /dev/sr[0-9] to  ```/usr/lib/udev/rules.d/99-media-automount.rules```, but it will not mount. Instead, I see the following error messages from the kernel:

```
Apr 08 18:01:41 media media-automount[24125]: /dev/sr0 has no known filesystem type, ignoring mount request
Apr 08 18:01:41 media media-automount[24132]: device doesn't exist anymore or is not a block device: /dev/sr0
```
I had also these error messages earlier:
```
Apr 08 08:32:00 media kernel: sr 1:0:0:0: [sr0] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=0s
Apr 08 08:32:00 media kernel: sr 1:0:0:0: [sr0] tag#0 Sense Key : Illegal Request [current] 
Apr 08 08:32:00 media kernel: sr 1:0:0:0: [sr0] tag#0 Add. Sense: Read of scrambled sector without authentication
Apr 08 08:32:00 media kernel: sr 1:0:0:0: [sr0] tag#0 CDB: Read(10) 28 00 00 00 04 00 00 00 02 00 00 00
Apr 08 08:32:00 media kernel: I/O error, dev sr0, sector 4096 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 2
```

I am aware of CSS, but I do not understand why the manual mount is working. Is what I am trying to do even possible?

**Comment by Ferk** [comment]
The TYPE is missing. This seems similar to #15 

If you run `blkid`, does the `/dev/sr0` device come up?

**Comment by ocroquette** [comment]
Thanks for the feedback. I don’t know what changed, but now it is working. I will report back if the problem occurs again.
