### ISSUE TITLE
suggested improvements

### ISSUE THREAD

**Issue by archenemies** [Ferk/udev-media-automount#4]
Passing `--no-block` here makes my startup go a lot faster:

    diff --git a/media-automount.rules b/media-automount.rules
    index a45fd30..cb1b9e8 100644
    --- a/media-automount.rules
    +++ b/media-automount.rules
    @@ -8,8 +8,8 @@
     # mounting has to be done as a separate "service"

     # mount the device when added
    -KERNEL=="sd[a-z]*", ACTION=="add",     RUN+="/bin/systemctl restart media-automount@%k.service"
    +KERNEL=="sd[a-z]*", ACTION=="add",     RUN+="/bin/systemctl restart --no-block media-automount@%k.service"

     # clean up after device removal
    -KERNEL=="sd[a-z]*", ACTION=="remove",  RUN+="/bin/systemctl restart media-automount@%k.service"
    +KERNEL=="sd[a-z]*", ACTION=="remove",  RUN+="/bin/systemctl restart --no-block media-automount@%k.service"

It helps to ignore comments in `/etc/fstab`:

    @@ -53,10 +53,14 @@ fi
     # Load additional info for the block device
     eval $(blkid -po export $dev)

    +grep_fstab () {
    +    grep -v '^\s*#' /etc/fstab | grep "$@"
    +}
    +
     # Check /etc/fstab for an entry corresponding to the device
    -[ "$UUID" ] && fstab=$(grep /etc/fstab -e "${UUID/\-/\\\-}") || \
    -[ "$LABEL" ] && fstab=$(grep /etc/fstab -e "${LABEL/\-/\\\-}") || \
    -fstab=$(grep /etc/fstab -e "^[ \t]*$dev[ \t]")
    +[ "$UUID" ] && fstab=$(grep_fstab -e "${UUID/\-/\\\-}") || \
    +[ "$LABEL" ] && fstab=$(grep_fstab -e "${LABEL/\-/\\\-}") || \
    +fstab=$(grep_fstab -e "^[ \t]*$dev[ \t]")

     # Don't manage devices that are already in fstab
     if [ "$fstab" ]

On all my systems, systemd stuff is in /bin/ not /usr/bin/:

    diff --git a/Makefile b/Makefile
    index 61a416e..b6e5916 100644
    --- a/Makefile
    +++ b/Makefile
    @@ -1,6 +1,6 @@
     install:
    -       install -D media-automount.rules $(DESTDIR)/usr/lib/udev/rules.d/99-media-automount.rules
    +       install -D media-automount.rules $(DESTDIR)/lib/udev/rules.d/99-media-automount.rules
            install -D umount_dmenu $(DESTDIR)/usr/bin/umount_dmenu
            install -D media-automount $(DESTDIR)/usr/bin/media-automount
    -       install -D media-automount@.service $(DESTDIR)/usr/lib/systemd/system/media-automount@.service
    +       install -D media-automount@.service $(DESTDIR)/lib/systemd/system/media-automount@.service

    diff --git a/media-automount.rules b/media-automount.rules
    index 947b4a3..a45fd30 100644
    --- a/media-automount.rules
    +++ b/media-automount.rules
    @@ -8,8 +8,8 @@
     # mounting has to be done as a separate "service"

     # mount the device when added
    -KERNEL=="sd[a-z]*", ACTION=="add",     RUN+="/usr/bin/systemctl restart media-automount@%k.service"
    +KERNEL=="sd[a-z]*", ACTION=="add",     RUN+="/bin/systemctl restart media-automount@%k.service"

     # clean up after device removal
    -KERNEL=="sd[a-z]*", ACTION=="remove",  RUN+="/usr/bin/systemctl restart media-automount@%k.service"
    +KERNEL=="sd[a-z]*", ACTION=="remove",  RUN+="/bin/systemctl restart media-automount@%k.service"

I prefer not to pass `user` to mount since it implies `noexec`:

    diff --git a/media-automount b/media-automount
    index bce64af..97a4957 100755
    --- a/media-automount
    +++ b/media-automount
    @@ -4,7 +4,11 @@
     # Directory to use for mounting the devices
     mdir=/media/
     # Default options to use for mounting
    -mopts='errors=remount-ro,relatime,utf8,user'
    +mopts='errors=remount-ro,relatime'

     [[ $EUID != 0 ]] && {
         echo "This tool requires root permissions"

**Comment by markstos** [comment]
It would also be nice if `umount_dmenu` didn't require root permission to run, but instead prompted for a root pw or sudo just before an umount action was called.

**Comment by markstos** [comment]
> On all my systems, systemd stuff is in /bin/ not /usr/bin/:

This package is targeting Arch Linux and on Arch `systemctl` is located at `/usr/bin/systemctl`

**Comment by markstos** [comment]
Ah, I'm new to Arch and just noticed that `/bin` and `/usr/bin` point to the same place, so it's a non-issue to change that on Arch. For reference the PKGBUILD file is here:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=udev-media-automount

**Comment by archenemies** [comment]
Thanks. Yes, I use Arch too, but also Raspbian. I think those changes make it work on both.

I commented out the GUI stuff too in my copy, and I just unmount with 'sudo', FWIW.

**Comment by Ferk** [comment]
Thank you very much @archenemies for the suggestions.

I think they are now all implemented. Except for the `$(DESTDIR)/usr/lib/systemd/` though now I updated it to `$(DESTDIR)$(PREFIX)/lib/systemd`, do let me know if that still causes issues. I'm not sure if there's a clean way to support all possible systemd locations.

For changing the mount options I added some configuration files, essentially, just some shell script files in `/etc/media-automount.d/` that will be imported so it's possible to alter the parameters (I added a [short description on the README](https://github.com/Ferk/udev-media-automount#configuration)).

**Comment by Ferk** [comment]
> It would also be nice if `umount_dmenu` didn't require root permission to run, but instead prompted for a root pw or sudo just before an umount action was called.

`umount_dmenu` is meant to be used as a GUI tool. You mean asking for a password through a GUI?

You can use `gksudo` instead of `sudo` if you want a graphical GUI for obtaining a password. Though I guess we could add a check in `umount_dmenu` to call itself with `gksudo` when available.

An alternative is to add a rule in `/etc/sudoers.d` so sudo doesn't prompt for a password at all when running umount_dmenu.

```
echo '%wheel ALL = NOPASSWD: /usr/bin/umount_dmenu' | sudo tee /etc/sudoers.d/umount_dmenuho '%wheel ALL = NOPASSWD: /usr/bin/umount_dmenu' | sudo tee /etc/sudoers.d/umount_dmenu
```
