### ISSUE TITLE
Script media-automount not properly working

### ISSUE THREAD

**Issue by AttFo-Niklas** [Ferk/udev-media-automount#7]
This script throws several errors on RPi Buster Image:

```
Jul 15 11:46:14 pios systemd[1]: Starting media-automount@sda1.service...
Jul 15 11:46:14 pios media-automount[1554]: /usr/bin/media-automount: 15: /usr/bin/media-automount: [[: not found
Jul 15 11:46:14 pios media-automount[1554]: /usr/bin/media-automount: 19: /usr/bin/media-automount: shopt: not found
Jul 15 11:46:14 pios media-automount[1554]: /usr/bin/media-automount: 71: /usr/bin/media-automount: Bad substitution
Jul 15 11:46:14 pios media-automount[1554]: /usr/bin/media-automount: 72: /usr/bin/media-automount: Bad substitution
Jul 15 11:46:14 pios media-automount[1554]: /usr/bin/media-automount: 91: /usr/bin/media-automount: source: not found
```
Media mounts but f.i. fstab parsing won't work!

I had to change the Shebang to '#!/bin/bash' to get this to work.

All the best!
lowPerformer

**Comment by clach04** [comment]
@AttFo-Niklas what is the Bourne shell on this machine? I wonder if /bin/sh is an incomplete implementation like dash?

**Comment by AttFo-Niklas** [comment]
/bin/sh links to dash, indeed.

**Comment by clach04** [comment]
Thanks for confirming @AttFo-Niklas , I wasn't near a machine when I replied. Just did a quick test and it would be trivial to fix that specific issue with a call to test and setting EUID via the `id` command. I didn't see any other instances of this construct in that script (see dmenu script) so this may be sufficient is bash is not available:

    localhost:~/code/udev-media-automount$ cat dash_experiment.sh
    #!/bin/sh

    # experiment based on https://github.com/Ferk/udev-media-automount/issues/7#issuecomment-1008655290

    echo EUID $EUID

    echo explit test call
    test ${EUID:=`id -u`} -ne 0  && {
        echo "This tool requires root permissions"
        echo exit here exit 1
    }

    echo code from line 15 of https://github.com/Ferk/udev-media-automount/blob/master/media-automount
    [[ $EUID != 0 ]] && {
        echo "This tool requires root permissions"
        exit 1
    }


    localhost:~/code/udev-media-automount$ dash dash_experiment.sh
    EUID
    explit test call
    This tool requires root permissions
    exit here exit 1
    code from line 15 of https://github.com/Ferk/udev-media-automount/blob/master/media-automount
    dash_experiment.sh: 14: [[: not found
    localhost:~/code/udev-media-automount$ bash dash_experiment.sh
    EUID 1000
    explit test call
    This tool requires root permissions
    exit here exit 1
    code from line 15 of https://github.com/Ferk/udev-media-automount/blob/master/media-automount
    This tool requires root permissions

**Comment by ballle98** [comment]
I have the same issue. on RPi Buster Image  It is interesting that it is only an issue on reboot and not if I restart the service after boot or unplug and re-insert the USB drive.  

`systemctl restart  media-automount@sda2.service`

**Comment by clach04** [comment]
Possibly more of a note to myself, (I think, not in front of my SBC at the moment) I've been using https://github.com/clach04/automount-usb for a while a (fixed) fork of https://github.com/raamsri/automount-usb

**Comment by Ferk** [comment]
I've fixed several bashisms and tested it on dash.

Thank you for reporting this and sorry for the delay in the responses.
