### ISSUE TITLE
Handle duplicate partition labels gracefully.

### ISSUE THREAD

**Issue by killemov** [Ferk/udev-media-automount#9]
I have some drives with a same-name labelled partition. When I insert these drives only the first one gets mounted. When I use these drives in a dock attached to a Pi with Kodi, Kodi simply adds a sequence number to the second mounted partition when mounting it. (my_partition, my_partition1, my_partition2, ...)

**Comment by Ferk** [comment]
I've added some logic to check for this. A number will be appended when there's already a directory existing there.

Thank you very much for reporting this and sorry again for the delay in the responses.
